version: '3.3'
services:
  covidtrttrialdesign:
    image: sc-registry.fredhutch.org/covidtrttrialdesign:latest
    networks:
      - proxy
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.covidtrttrialdesign.rule=Host(`seqtrttrials.fredhutch.org`)"
        - "traefik.http.routers.covidtrttrialdesign-secured.rule=Host(`seqtrttrials.fredhutch.org`)"
        - "traefik.http.routers.covidtrttrialdesign.entrypoints=web,web-secured"
        - "traefik.http.services.covidtrttrialdesign.loadbalancer.server.port=7777" # it seems you always need to give traefik a port so it 'notices' the service
        - "traefik.http.routers.covidtrttrialdesign.tls=true"
                          
networks:
  proxy:
    external: true


